export const dummyMenus = [
  {
    name: "Adobo",
    description:
      "A classic Filipino dish made with chicken or pork braised in soy sauce, vinegar, garlic, bay leaves, and peppercorns.",
    price: 180,
    servingSize: 1,
    category: "Chicken Dishes",
    dietaryInfo: ["Halal"],
    allergens: ["Soy"],
    isAvailable: true,
    mainImage: "https://example.com/images/adobo.jpg",
    images: [
      "https://example.com/images/adobo1.jpg",
      "https://example.com/images/adobo2.jpg",
      "https://example.com/images/adobo3.jpg",
      "https://example.com/images/adobo4.jpg",
    ],
  },
  {
    name: "Sinigang na Baboy",
    description:
      "A sour tamarind-based soup with tender pork, vegetables, and a refreshing tangy flavor.",
    price: 220,
    servingSize: 1,
    category: "Pork Dishes",
    dietaryInfo: [],
    allergens: [],
    isAvailable: true,
    mainImage: "https://example.com/images/sinigang.jpg",
    images: [
      "https://example.com/images/sinigang1.jpg",
      "https://example.com/images/sinigang2.jpg",
      "https://example.com/images/sinigang3.jpg",
      "https://example.com/images/sinigang4.jpg",
    ],
  },
  {
    name: "Pancit Canton",
    description:
      "A stir-fried noodle dish with egg noodles, shrimp, pork, and mixed vegetables, seasoned with soy sauce and calamansi.",
    price: 150,
    servingSize: 1,
    category: "Pasta & Noodles",
    dietaryInfo: [],
    allergens: ["Gluten", "Soy", "Shellfish"],
    isAvailable: true,
    mainImage: "https://example.com/images/pancit.jpg",
    images: [
      "https://example.com/images/pancit1.jpg",
      "https://example.com/images/pancit2.jpg",
      "https://example.com/images/pancit3.jpg",
      "https://example.com/images/pancit4.jpg",
    ],
  },
  {
    name: "Kare-Kare",
    description:
      "A rich peanut stew with oxtail, tripe, and vegetables, served with bagoong (fermented shrimp paste).",
    price: 250,
    servingSize: 1,
    category: "Beef Dishes",
    dietaryInfo: [],
    allergens: ["Peanuts", "Shellfish"],
    isAvailable: true,
    mainImage: "https://example.com/images/karekare.jpg",
    images: [
      "https://example.com/images/karekare1.jpg",
      "https://example.com/images/karekare2.jpg",
      "https://example.com/images/karekare3.jpg",
      "https://example.com/images/karekare4.jpg",
    ],
  },
  {
    name: "Halo-Halo",
    description:
      "A popular Filipino dessert with crushed ice, sweetened fruits, jellies, beans, leche flan, and evaporated milk.",
    price: 120,
    servingSize: 1,
    category: "Desserts & Sweets",
    dietaryInfo: ["Vegetarian"],
    allergens: ["Dairy"],
    isAvailable: true,
    mainImage: "https://example.com/images/halohalo.jpg",
    images: [
      "https://example.com/images/halohalo1.jpg",
      "https://example.com/images/halohalo2.jpg",
      "https://example.com/images/halohalo3.jpg",
      "https://example.com/images/halohalo4.jpg",
    ],
  },
  {
    name: "Lechon",
    description:
      "A whole roasted pig with crispy skin and tender meat, often the centerpiece of Filipino celebrations.",
    price: 1200,
    servingSize: 10,
    category: "Pork Dishes",
    dietaryInfo: [],
    allergens: [],
    isAvailable: true,
    mainImage: "https://example.com/images/lechon.jpg",
    images: [
      "https://example.com/images/lechon1.jpg",
      "https://example.com/images/lechon2.jpg",
      "https://example.com/images/lechon3.jpg",
      "https://example.com/images/lechon4.jpg",
    ],
  },
  {
    name: "Chicken Inasal",
    description:
      "Grilled chicken marinated in a mixture of calamansi, vinegar, lemongrass, and annatto, served with a tangy dip.",
    price: 200,
    servingSize: 1,
    category: "Chicken Dishes",
    dietaryInfo: ["Halal"],
    allergens: [],
    isAvailable: true,
    mainImage: "https://example.com/images/inasal.jpg",
    images: [
      "https://example.com/images/inasal1.jpg",
      "https://example.com/images/inasal2.jpg",
      "https://example.com/images/inasal3.jpg",
      "https://example.com/images/inasal4.jpg",
    ],
  },
  {
    name: "Beef Caldereta",
    description:
      "A hearty beef stew cooked with tomato sauce, potatoes, carrots, bell peppers, and a hint of liver spread.",
    price: 280,
    servingSize: 1,
    category: "Beef Dishes",
    dietaryInfo: [],
    allergens: [],
    isAvailable: true,
    mainImage: "https://example.com/images/caldereta.jpg",
    images: [
      "https://example.com/images/caldereta1.jpg",
      "https://example.com/images/caldereta2.jpg",
      "https://example.com/images/caldereta3.jpg",
      "https://example.com/images/caldereta4.jpg",
    ],
  },
  {
    name: "Lumpiang Shanghai",
    description:
      "Crispy spring rolls filled with ground pork, carrots, and onions, served with a sweet and sour dipping sauce.",
    price: 100,
    servingSize: 5,
    category: "Soup & Hot Appetizers",
    dietaryInfo: [],
    allergens: ["Gluten"], // Assuming wrapper contains wheat
    isAvailable: true,
    mainImage: "https://example.com/images/lumpia.jpg",
    images: [
      "https://example.com/images/lumpia1.jpg",
      "https://example.com/images/lumpia2.jpg",
      "https://example.com/images/lumpia3.jpg",
      "https://example.com/images/lumpia4.jpg",
    ],
  },
  {
    name: "Bistek Tagalog",
    description:
      "Thinly sliced beef marinated in soy sauce and calamansi, pan-fried with onions for a savory-tangy flavor.",
    price: 240,
    servingSize: 1,
    category: "Beef Dishes",
    dietaryInfo: [],
    allergens: ["Soy"],
    isAvailable: true,
    mainImage: "https://example.com/images/bistek.jpg",
    images: [
      "https://example.com/images/bistek1.jpg",
      "https://example.com/images/bistek2.jpg",
      "https://example.com/images/bistek3.jpg",
      "https://example.com/images/bistek4.jpg",
    ],
  },
  {
    name: "Pork Sisig",
    description:
      "A sizzling dish made from chopped pork face and ears, seasoned with calamansi, onions, and chili peppers.",
    price: 190,
    servingSize: 1,
    category: "Pork Dishes",
    dietaryInfo: [],
    allergens: [],
    isAvailable: true,
    mainImage: "https://example.com/images/sisig.jpg",
    images: [
      "https://example.com/images/sisig1.jpg",
      "https://example.com/images/sisig2.jpg",
      "https://example.com/images/sisig3.jpg",
      "https://example.com/images/sisig4.jpg",
    ],
  },
  {
    name: "Tinola",
    description:
      "A light chicken soup with green papaya, malunggay leaves, and ginger, offering a comforting and healthy taste.",
    price: 180,
    servingSize: 1,
    category: "Soup & Hot Appetizers",
    dietaryInfo: ["Gluten-Free"],
    allergens: [],
    isAvailable: true,
    mainImage: "https://example.com/images/tinola.jpg",
    images: [
      "https://example.com/images/tinola1.jpg",
      "https://example.com/images/tinola2.jpg",
      "https://example.com/images/tinola3.jpg",
      "https://example.com/images/tinola4.jpg",
    ],
  },
  {
    name: "Menudo",
    description:
      "A pork stew with liver, potatoes, carrots, and bell peppers in a rich tomato-based sauce.",
    price: 210,
    servingSize: 1,
    category: "Pork Dishes",
    dietaryInfo: [],
    allergens: [],
    isAvailable: true,
    mainImage: "https://example.com/images/menudo.jpg",
    images: [
      "https://example.com/images/menudo1.jpg",
      "https://example.com/images/menudo2.jpg",
      "https://example.com/images/menudo3.jpg",
      "https://example.com/images/menudo4.jpg",
    ],
  },
  {
    name: "Buko Pandan",
    description:
      "A refreshing dessert made with young coconut, pandan jelly, cream, and sweetened condensed milk.",
    price: 130,
    servingSize: 1,
    category: "Desserts & Sweets",
    dietaryInfo: ["Vegetarian"],
    allergens: ["Dairy"],
    isAvailable: true,
    mainImage: "https://example.com/images/bukopandan.jpg",
    images: [
      "https://example.com/images/bukopandan1.jpg",
      "https://example.com/images/bukopandan2.jpg",
      "https://example.com/images/bukopandan3.jpg",
      "https://example.com/images/bukopandan4.jpg",
    ],
  },
  {
    name: "Embutido",
    description:
      "A Filipino-style meatloaf made with ground pork, sausages, eggs, raisins, and carrots, steamed to perfection.",
    price: 160,
    servingSize: 1,
    category: "Pork Dishes",
    dietaryInfo: [],
    allergens: ["Eggs"],
    isAvailable: true,
    mainImage: "https://example.com/images/embutido.jpg",
    images: [
      "https://example.com/images/embutido1.jpg",
      "https://example.com/images/embutido2.jpg",
      "https://example.com/images/embutido3.jpg",
      "https://example.com/images/embutido4.jpg",
    ],
  },
  {
    name: "Adobo",
    description:
      "A classic Filipino dish made with chicken or pork braised in soy sauce, vinegar, garlic, bay leaves, and peppercorns.",
    price: 180,
    servingSize: 1,
    category: "Chicken Dishes",
    dietaryInfo: ["Halal"],
    allergens: ["Soy"],
    isAvailable: true,
    mainImage: "https://example.com/images/adobo.jpg",
    images: [
      "https://example.com/images/adobo1.jpg",
      "https://example.com/images/adobo2.jpg",
      "https://example.com/images/adobo3.jpg",
      "https://example.com/images/adobo4.jpg",
    ],
  },
  {
    name: "Sinigang na Baboy",
    description:
      "A sour tamarind-based soup with tender pork, vegetables, and a refreshing tangy flavor.",
    price: 220,
    servingSize: 1,
    category: "Soup & Hot Appetizers",
    dietaryInfo: [],
    allergens: [],
    isAvailable: true,
    mainImage: "https://example.com/images/sinigang.jpg",
    images: [
      "https://example.com/images/sinigang1.jpg",
      "https://example.com/images/sinigang2.jpg",
      "https://example.com/images/sinigang3.jpg",
      "https://example.com/images/sinigang4.jpg",
    ],
  },
  {
    name: "Pancit Canton",
    description:
      "A stir-fried noodle dish with egg noodles, shrimp, pork, and mixed vegetables, seasoned with soy sauce and calamansi.",
    price: 150,
    servingSize: 1,
    category: "Pasta & Noodles",
    dietaryInfo: [],
    allergens: ["Gluten", "Soy", "Shellfish"],
    isAvailable: true,
    mainImage: "https://example.com/images/pancit.jpg",
    images: [
      "https://example.com/images/pancit1.jpg",
      "https://example.com/images/pancit2.jpg",
      "https://example.com/images/pancit3.jpg",
      "https://example.com/images/pancit4.jpg",
    ],
  },
  {
    name: "Kare-Kare",
    description:
      "A rich peanut stew with oxtail, tripe, and vegetables, served with bagoong (fermented shrimp paste).",
    price: 250,
    servingSize: 1,
    category: "Beef Dishes",
    dietaryInfo: [],
    allergens: ["Peanuts", "Shellfish"],
    isAvailable: true,
    mainImage: "https://example.com/images/karekare.jpg",
    images: [
      "https://example.com/images/karekare1.jpg",
      "https://example.com/images/karekare2.jpg",
      "https://example.com/images/karekare3.jpg",
      "https://example.com/images/karekare4.jpg",
    ],
  },
  {
    name: "Halo-Halo",
    description:
      "A popular Filipino dessert with crushed ice, sweetened fruits, jellies, beans, leche flan, and evaporated milk.",
    price: 120,
    servingSize: 1,
    category: "Desserts & Sweets",
    dietaryInfo: ["Vegetarian"],
    allergens: ["Dairy"],
    isAvailable: true,
    mainImage: "https://example.com/images/halohalo.jpg",
    images: [
      "https://example.com/images/halohalo1.jpg",
      "https://example.com/images/halohalo2.jpg",
      "https://example.com/images/halohalo3.jpg",
      "https://example.com/images/halohalo4.jpg",
    ],
  },
];
