export const buffetPackages = [
  {
    id: "buffet-a",
    name: "Set A - Basic Feast",
    description:
      "A simple yet satisfying selection of Filipino favorites for small gatherings.",
    pricePerPax: 350,
    minimumPax: 20,
    recommendedPax: 30,
    maximumPax: 50,
    options: [
      { category: "Soup", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Noodle", count: 1 },
    ],
    inclusions: [
      "Basic table setup",
      "Disposable utensils and plates",
      "Service staff (2 personnel)",
      "Food warmers and serving utensils",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
  },
  {
    id: "buffet-b",
    name: "Set B - Family Celebration",
    description:
      "A hearty selection of dishes perfect for family celebrations and small parties.",
    pricePerPax: 450,
    minimumPax: 30,
    recommendedPax: 50,
    maximumPax: 80,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Noodle", count: 1 },
    ],
    inclusions: [
      "Enhanced table setup",
      "Disposable utensils and plates",
      "Service staff (3 personnel)",
      "Food warmers and serving utensils",
      "Basic dessert station",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
  },
  {
    id: "buffet-c",
    name: "Set C - Fiesta Favorites",
    description:
      "A complete Filipino fiesta experience with a wide variety of traditional dishes.",
    pricePerPax: 550,
    minimumPax: 50,
    recommendedPax: 80,
    maximumPax: 120,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Noodle", count: 1 },
    ],
    inclusions: [
      "Premium table setup",
      "Quality disposable utensils and plates",
      "Service staff (4 personnel)",
      "Food warmers and serving utensils",
      "Dessert station with 2 options",
      "Welcome drinks",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
  },
  {
    id: "buffet-d",
    name: "Set D - Premium Celebration",
    description:
      "An elevated dining experience featuring premium Filipino dishes for special occasions.",
    pricePerPax: 650,
    minimumPax: 50,
    recommendedPax: 100,
    maximumPax: 150,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 2 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Seafood", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Beverage", count: 1 },
    ],
    inclusions: [
      "Elegant table setup with centerpieces",
      "Quality disposable utensils and plates",
      "Service staff (5 personnel)",
      "Food warmers and serving utensils",
      "Dessert station with 3 options",
      "Welcome drinks and iced tea",
      "Basic coffee station",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
  },
  {
    id: "buffet-e",
    name: "Set E - Grand Feast",
    description:
      "A grand Filipino feast featuring a comprehensive selection of dishes for large celebrations.",
    pricePerPax: 750,
    minimumPax: 80,
    recommendedPax: 120,
    maximumPax: 200,
    options: [
      { category: "Soup", count: 2 },
      { category: "Salad", count: 2 },
      { category: "Chicken", count: 2 },
      { category: "Pork", count: 2 },
      { category: "Beef", count: 1 },
      { category: "Seafood", count: 1 },
      { category: "Vegetable", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 2 },
      { category: "Beverage", count: 2 },
    ],
    inclusions: [
      "Premium table setup with floral arrangements",
      "Quality disposable utensils and plates",
      "Service staff (7 personnel)",
      "Food warmers and serving utensils",
      "Dessert station with 4 options",
      "Welcome drinks and unlimited iced tea",
      "Coffee and tea station",
      "Fruit station",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
  },
  {
    id: "buffet-f",
    name: "Set F - Royal Filipino Banquet",
    description:
      "The ultimate Filipino banquet experience featuring our finest dishes and premium service.",
    pricePerPax: 950,
    minimumPax: 100,
    recommendedPax: 150,
    maximumPax: 300,
    options: [
      { category: "Soup", count: 2 },
      { category: "Salad", count: 2 },
      { category: "Chicken", count: 2 },
      { category: "Pork", count: 2 },
      { category: "Beef", count: 2 },
      { category: "Seafood", count: 2 },
      { category: "Vegetable", count: 2 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 3 },
      { category: "Beverage", count: 3 },
    ],
    inclusions: [
      "Luxury table setup with premium decorations",
      "Fine dining utensils and plates",
      "Service staff (10 personnel)",
      "Food warmers and serving utensils",
      "Premium dessert station with 5 options",
      "Welcome cocktails and unlimited beverages",
      "Premium coffee and tea station",
      "Fruit and cheese station",
      "Live cooking station",
      "Ice cream station",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
  },
];

export const platedPackages = [
  {
    id: "plated-a",
    name: "Plated Set A - Basic Feast",
    description:
      "A simple yet satisfying selection of Filipino favorites for small gatherings.",
    pricePerPax: 370, // 350 + (4 * 100) / 20
    minimumPax: 20,
    recommendedPax: 30,
    maximumPax: 50,
    serviceHours: 4,
    serviceCharge: 100,
    options: [
      { category: "Soup", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Noodle", count: 1 },
    ],

    inclusions: [
      "Basic table setup",
      "Disposable utensils and plates",
      "Service staff (2 personnel)",
      "Food warmers and serving utensils",
      "4 hours of table service",
      "Professional waitstaff",
      "Table-side service",
      "Course-by-course serving",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
  },
  {
    id: "plated-b",
    name: "Plated Set B - Family Celebration",
    description:
      "A hearty selection of dishes perfect for family celebrations and small parties.",
    pricePerPax: 465, // 450 + (4.5 * 100) / 30
    minimumPax: 30,
    recommendedPax: 50,
    maximumPax: 80,
    serviceHours: 4.5,
    serviceCharge: 100,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Noodle", count: 1 },
    ],
    inclusions: [
      "Enhanced table setup",
      "Disposable utensils and plates",
      "Service staff (3 personnel)",
      "Food warmers and serving utensils",
      "Basic dessert station",
      "4.5 hours of table service",
      "Professional waitstaff",
      "Table-side service",
      "Course-by-course serving",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
  },
  {
    id: "plated-c",
    name: "Plated Set C - Fiesta Favorites",
    description:
      "A complete Filipino fiesta experience with a wide variety of traditional dishes.",
    pricePerPax: 560, // 550 + (5 * 100) / 50
    minimumPax: 50,
    recommendedPax: 80,
    maximumPax: 120,
    serviceHours: 5,
    serviceCharge: 100,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Noodle", count: 1 },
    ],
    inclusions: [
      "Premium table setup",
      "Quality disposable utensils and plates",
      "Service staff (4 personnel)",
      "Food warmers and serving utensils",
      "Dessert station with 2 options",
      "Welcome drinks",
      "5 hours of table service",
      "Professional waitstaff",
      "Table-side service",
      "Course-by-course serving",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
  },
  {
    id: "plated-d",
    name: "Plated Set D - Premium Celebration",
    description:
      "An elevated dining experience featuring premium Filipino dishes for special occasions.",
    pricePerPax: 661, // 650 + (5.5 * 100) / 50
    minimumPax: 50,
    recommendedPax: 100,
    maximumPax: 150,
    serviceHours: 5.5,
    serviceCharge: 100,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 2 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Seafood", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Beverage", count: 1 },
    ],
    inclusions: [
      "Elegant table setup with centerpieces",
      "Quality disposable utensils and plates",
      "Service staff (5 personnel)",
      "Food warmers and serving utensils",
      "Dessert station with 3 options",
      "Welcome drinks and iced tea",
      "Basic coffee station",
      "5.5 hours of table service",
      "Professional waitstaff",
      "Table-side service",
      "Course-by-course serving",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
  },
  {
    id: "plated-e",
    name: "Plated Set E - Grand Feast",
    description:
      "A grand Filipino feast featuring a comprehensive selection of dishes for large celebrations.",
    pricePerPax: 758, // 750 + (6 * 100) / 80
    minimumPax: 80,
    recommendedPax: 120,
    maximumPax: 200,
    serviceHours: 6,
    serviceCharge: 100,
    options: [
      { category: "Soup", count: 2 },
      { category: "Salad", count: 2 },
      { category: "Chicken", count: 2 },
      { category: "Pork", count: 2 },
      { category: "Beef", count: 1 },
      { category: "Seafood", count: 1 },
      { category: "Vegetable", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 2 },
      { category: "Beverage", count: 2 },
    ],
    inclusions: [
      "Premium table setup with floral arrangements",
      "Quality disposable utensils and plates",
      "Service staff (7 personnel)",
      "Food warmers and serving utensils",
      "Dessert station with 4 options",
      "Welcome drinks and unlimited iced tea",
      "Coffee and tea station",
      "Fruit station",
      "6 hours of table service",
      "Professional waitstaff",
      "Table-side service",
      "Course-by-course serving",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
  },
  {
    id: "plated-f",
    name: "Plated Set F - Royal Filipino Banquet",
    description:
      "The ultimate Filipino banquet experience featuring our finest dishes and premium service.",
    pricePerPax: 957, // 950 + (6.5 * 100) / 100
    minimumPax: 100,
    recommendedPax: 150,
    maximumPax: 300,
    serviceHours: 6.5,
    serviceCharge: 100,
    options: [
      { category: "Soup", count: 2 },
      { category: "Salad", count: 2 },
      { category: "Chicken", count: 2 },
      { category: "Pork", count: 2 },
      { category: "Beef", count: 2 },
      { category: "Seafood", count: 2 },
      { category: "Vegetable", count: 2 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 3 },
      { category: "Beverage", count: 3 },
    ],
    inclusions: [
      "Luxury table setup with premium decorations",
      "Fine dining utensils and plates",
      "Service staff (10 personnel)",
      "Food warmers and serving utensils",
      "Premium dessert station with 5 options",
      "Welcome cocktails and unlimited beverages",
      "Premium coffee and tea station",
      "Fruit and cheese station",
      "Live cooking station",
      "Ice cream station",
      "6.5 hours of table service",
      "Professional waitstaff",
      "Table-side service",
      "Course-by-course serving",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
  },
];
