import { Types } from "mongoose";

const reservationDummy = [
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678901"), // John Doe
    eventDetails: {
      type: "birthday",
      date: new Date(2025, 4, 10),
      time: new Date(2025, 4, 10, 15, 0),
      numberOfGuests: 40,
      venue: "Manila Bay Club",
      serviceType: "Buffet",
      serviceHours: 4,
    },
    menuSelection: {
      soupOptions: ["Sinigang na Baboy"],
      saladOptions: ["Ensaladang Talong"],
      chickenOptions: ["Chicken Adobo"],
      porkOptions: [],
      beefOptions: ["Beef Caldereta"],
      seafoodOptions: [],
      vegetableOptions: ["Pinakbet"],
      noodleOptions: ["Pancit Canton"],
      dessertOptions: ["Halo-Halo"],
      beverageOptions: ["Sago't Gulaman", "Calamansi Juice"],
    },
    specialRequests: "Extra dessert",
    costDetails: {
      totalReservationCost: 20000,
      minimumDownPayment: 4000,
      downPaymentPaid: 4000,
    },
    status: "confirmed",
    paymentStatus: "partially_paid",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-03"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678902"), // Jane Smith
    eventDetails: {
      type: "wedding",
      date: new Date(2025, 6, 15),
      time: new Date(2025, 6, 15, 18, 0),
      numberOfGuests: 60,
      venue: "Tagaytay Villa",
      serviceType: "Buffet",
      serviceHours: 6,
    },
    menuSelection: {
      soupOptions: ["Bulalo"],
      saladOptions: [],
      chickenOptions: ["Chicken Inasal", "Chicken Adobo"],
      porkOptions: ["Lechon Kawali"],
      beefOptions: [],
      seafoodOptions: ["Beef Caldereta"],
      vegetableOptions: ["Ginataang Kalabasa at Sitaw"],
      noodleOptions: [],
      dessertOptions: ["Leche Flan", "Biko"],
      beverageOptions: ["Buko Juice"],
    },
    specialRequests: "More rice",
    costDetails: {
      totalReservationCost: 30000,
      minimumDownPayment: 6000,
      downPaymentPaid: 0,
    },
    status: "pending",
    paymentStatus: "pending",
    createdAt: new Date("2025-03-02"),
    updatedAt: new Date("2025-03-02"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678903"), // Michael Brown
    eventDetails: {
      type: "anniversary",
      date: new Date(2025, 8, 20),
      time: new Date(2025, 8, 20, 19, 0),
      numberOfGuests: 50,
      venue: "BGC Pavilion",
      serviceType: "Plated Service",
      serviceHours: 5,
    },
    menuSelection: {
      soupOptions: [],
      saladOptions: ["Kinilaw na Tuna"],
      chickenOptions: [],
      porkOptions: ["Pork Adobo", "Sisig"],
      beefOptions: ["Beef Mechado"],
      seafoodOptions: ["Beef Kare-Kare"],
      vegetableOptions: [],
      noodleOptions: ["Pancit Bihon"],
      dessertOptions: ["Bibingka"],
      beverageOptions: ["Tsokolate", "Calamansi Juice"],
    },
    specialRequests: "",
    costDetails: {
      totalReservationCost: 25000,
      minimumDownPayment: 5000,
      downPaymentPaid: 5000,
    },
    status: "confirmed",
    paymentStatus: "partially_paid",
    createdAt: new Date("2025-03-03"),
    updatedAt: new Date("2025-03-05"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678904"), // Emily Davis
    eventDetails: {
      type: "corporate",
      date: new Date(2025, 10, 5),
      time: new Date(2025, 10, 5, 9, 0),
      numberOfGuests: 80,
      venue: "Makati Tower",
      serviceType: "Buffet",
      serviceHours: 8,
    },
    menuSelection: {
      soupOptions: ["Tinolang Manok", "Nilagang Baka"],
      saladOptions: ["Enseladang Mangga"],
      chickenOptions: ["Chicken Afritada"],
      porkOptions: ["Crispy Pata"],
      beefOptions: ["Bistek Tagalog"],
      seafoodOptions: [],
      vegetableOptions: ["Laing"],
      noodleOptions: [],
      dessertOptions: ["Halo-Halo", "Leche Flan"],
      beverageOptions: ["Sago't Gulaman"],
    },
    specialRequests: "Vegetarian options",
    costDetails: {
      totalReservationCost: 40000,
      minimumDownPayment: 8000,
      downPaymentPaid: 0,
    },
    status: "pending",
    paymentStatus: "pending",
    createdAt: new Date("2025-03-04"),
    updatedAt: new Date("2025-03-04"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678905"), // William Johnson
    eventDetails: {
      type: "birthday",
      date: new Date(2025, 5, 25),
      time: new Date(2025, 5, 25, 14, 0),
      numberOfGuests: 35,
      venue: "Quezon City Park",
      serviceType: "Plated Service",
      serviceHours: 4,
    },
    menuSelection: {
      soupOptions: ["Sinigang na Baboy"],
      saladOptions: [],
      chickenOptions: ["Fried Chicken with Gravy"],
      porkOptions: [],
      beefOptions: [],
      seafoodOptions: ["Beef Mechado", "Beef Kare-Kare"],
      vegetableOptions: ["Ginisang Ampalaya"],
      noodleOptions: ["Pancit Palabok"],
      dessertOptions: [],
      beverageOptions: ["Buko Juice"],
    },
    specialRequests: "Gluten-free options",
    costDetails: {
      totalReservationCost: 17500,
      minimumDownPayment: 3500,
      downPaymentPaid: 3500,
    },
    status: "confirmed",
    paymentStatus: "partially_paid",
    createdAt: new Date("2025-03-05"),
    updatedAt: new Date("2025-03-07"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678906"), // Sarah Wilson
    eventDetails: {
      type: "wedding",
      date: new Date(2025, 7, 15),
      time: new Date(2025, 7, 15, 17, 0),
      numberOfGuests: 70,
      venue: "Cebu Resort",
      serviceType: "Buffet",
      serviceHours: 6,
    },
    menuSelection: {
      soupOptions: ["Bulalo"],
      saladOptions: ["Lato Salad"],
      chickenOptions: [],
      porkOptions: ["Lechon Kawali", "Sisig"],
      beefOptions: ["Beef Caldereta"],
      seafoodOptions: [],
      vegetableOptions: [],
      noodleOptions: ["Pancit Malabon"],
      dessertOptions: ["Biko"],
      beverageOptions: ["Tsokolate", "Calamansi Juice"],
    },
    specialRequests: "Extra lechon",
    costDetails: {
      totalReservationCost: 35000,
      minimumDownPayment: 7000,
      downPaymentPaid: 0,
    },
    status: "pending",
    paymentStatus: "pending",
    createdAt: new Date("2025-03-06"),
    updatedAt: new Date("2025-03-06"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678907"), // David Lee
    eventDetails: {
      type: "anniversary",
      date: new Date(2025, 9, 10),
      time: new Date(2025, 9, 10, 18, 0),
      numberOfGuests: 45,
      venue: "Pasay Hall",
      serviceType: "Buffet",
      serviceHours: 5,
    },
    menuSelection: {
      soupOptions: [],
      saladOptions: ["Ensaladang Talong", "Kinilaw na Tuna"],
      chickenOptions: ["Chicken Inasal"],
      porkOptions: [],
      beefOptions: ["Beef Mechado"],
      seafoodOptions: ["Beef Caldereta"],
      vegetableOptions: ["Pinakbet"],
      noodleOptions: [],
      dessertOptions: ["Halo-Halo", "Bibingka"],
      beverageOptions: ["Sago't Gulaman"],
    },
    specialRequests: "Low-sodium options",
    costDetails: {
      totalReservationCost: 22500,
      minimumDownPayment: 4500,
      downPaymentPaid: 4500,
    },
    status: "confirmed",
    paymentStatus: "partially_paid",
    createdAt: new Date("2025-03-07"),
    updatedAt: new Date("2025-03-09"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678908"), // Laura Martinez
    eventDetails: {
      type: "corporate",
      date: new Date(2025, 11, 20),
      time: new Date(2025, 11, 20, 10, 0),
      numberOfGuests: 90,
      venue: "Ortigas Center",
      serviceType: "Plated Service",
      serviceHours: 10,
    },
    menuSelection: {
      soupOptions: ["Tinolang Manok"],
      saladOptions: ["Enseladang Mangga"],
      chickenOptions: ["Chicken Adobo", "Chicken Afritada"],
      porkOptions: ["Pork Adobo"],
      beefOptions: [],
      seafoodOptions: ["Beef Kare-Kare"],
      vegetableOptions: ["Laing"],
      noodleOptions: ["Pancit Canton"],
      dessertOptions: ["Leche Flan"],
      beverageOptions: ["Buko Juice", "Tsokolate"],
    },
    specialRequests: "Halal options",
    costDetails: {
      totalReservationCost: 45000,
      minimumDownPayment: 9000,
      downPaymentPaid: 9000,
    },
    status: "confirmed",
    paymentStatus: "partially_paid",
    createdAt: new Date("2025-03-08"),
    updatedAt: new Date("2025-03-10"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678909"), // James Taylor
    eventDetails: {
      type: "birthday",
      date: new Date(2025, 4, 30),
      time: new Date(2025, 4, 30, 15, 0),
      numberOfGuests: 30,
      venue: "Laguna Garden",
      serviceType: "Buffet",
      serviceHours: 4,
    },
    menuSelection: {
      soupOptions: ["Nilagang Baka"],
      saladOptions: [],
      chickenOptions: ["Chicken Inasal"],
      porkOptions: [],
      beefOptions: ["Bistek Tagalog"],
      seafoodOptions: [],
      vegetableOptions: ["Ginisang Ampalaya"],
      noodleOptions: ["Pancit Bihon"],
      dessertOptions: ["Halo-Halo"],
      beverageOptions: ["Calamansi Juice"],
    },
    specialRequests: "No spicy food",
    costDetails: {
      totalReservationCost: 15000,
      minimumDownPayment: 3000,
      downPaymentPaid: 0,
    },
    status: "pending",
    paymentStatus: "pending",
    createdAt: new Date("2025-03-09"),
    updatedAt: new Date("2025-03-09"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b1234567890a"), // Olivia Anderson
    eventDetails: {
      type: "wedding",
      date: new Date(2025, 6, 20),
      time: new Date(2025, 6, 20, 17, 0),
      numberOfGuests: 65,
      venue: "Batangas Resort",
      serviceType: "Buffet",
      serviceHours: 6,
    },
    menuSelection: {
      soupOptions: ["Sinigang na Baboy"],
      saladOptions: ["Lato Salad"],
      chickenOptions: ["Chicken Adobo"],
      porkOptions: ["Crispy Pata"],
      beefOptions: [],
      seafoodOptions: ["Beef Mechado"],
      vegetableOptions: ["Pinakbet"],
      noodleOptions: [],
      dessertOptions: ["Biko", "Bibingka"],
      beverageOptions: ["Sago't Gulaman"],
    },
    specialRequests: "Extra crispy pata",
    costDetails: {
      totalReservationCost: 32500,
      minimumDownPayment: 6500,
      downPaymentPaid: 6500,
    },
    status: "confirmed",
    paymentStatus: "partially_paid",
    createdAt: new Date("2025-03-10"),
    updatedAt: new Date("2025-03-12"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678901"), // John Doe (repeated)
    eventDetails: {
      type: "anniversary",
      date: new Date(2025, 8, 15),
      time: new Date(2025, 8, 15, 18, 0),
      numberOfGuests: 55,
      venue: "Davao Pavilion",
      serviceType: "Buffet",
      serviceHours: 5,
    },
    menuSelection: {
      soupOptions: ["Bulalo"],
      saladOptions: ["Kinilaw na Tuna"],
      chickenOptions: [],
      porkOptions: ["Sisig"],
      beefOptions: ["Beef Kare-Kare"],
      seafoodOptions: [],
      vegetableOptions: ["Laing"],
      noodleOptions: ["Pancit Palabok"],
      dessertOptions: ["Halo-Halo"],
      beverageOptions: ["Tsokolate"],
    },
    specialRequests: "More seafood",
    costDetails: {
      totalReservationCost: 27500,
      minimumDownPayment: 5500,
      downPaymentPaid: 0,
    },
    status: "pending",
    paymentStatus: "pending",
    createdAt: new Date("2025-03-11"),
    updatedAt: new Date("2025-03-11"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678902"), // Jane Smith (repeated)
    eventDetails: {
      type: "corporate",
      date: new Date(2025, 10, 15),
      time: new Date(2025, 10, 15, 9, 0),
      numberOfGuests: 100,
      venue: "Clark Freeport",
      serviceType: "Plated Service",
      serviceHours: 8,
    },
    menuSelection: {
      soupOptions: ["Tinolang Manok", "Nilagang Baka"],
      saladOptions: ["Ensaladang Talong"],
      chickenOptions: ["Chicken Afritada"],
      porkOptions: ["Pork Adobo"],
      beefOptions: ["Beef Caldereta"],
      seafoodOptions: ["Beef Mechado"],
      vegetableOptions: [],
      noodleOptions: ["Pancit Canton"],
      dessertOptions: ["Leche Flan"],
      beverageOptions: ["Buko Juice", "Sago't Gulaman"],
    },
    specialRequests: "Vegan options",
    costDetails: {
      totalReservationCost: 50000,
      minimumDownPayment: 10000,
      downPaymentPaid: 10000,
    },
    status: "confirmed",
    paymentStatus: "partially_paid",
    createdAt: new Date("2025-03-12"),
    updatedAt: new Date("2025-03-14"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678904"), // Emily Davis (repeated)
    eventDetails: {
      type: "wedding",
      date: new Date(2025, 7, 25),
      time: new Date(2025, 7, 25, 17, 0),
      numberOfGuests: 75,
      venue: "Palawan Beach",
      serviceType: "Buffet",
      serviceHours: 6,
    },
    menuSelection: {
      soupOptions: ["Bulalo"],
      saladOptions: ["Lato Salad"],
      chickenOptions: ["Chicken Adobo"],
      porkOptions: ["Lechon Kawali"],
      beefOptions: [],
      seafoodOptions: ["Beef Kare-Kare", "Beef Caldereta"],
      vegetableOptions: [],
      noodleOptions: ["Pancit Malabon"],
      dessertOptions: ["Biko"],
      beverageOptions: ["Tsokolate"],
    },
    specialRequests: "Extra crispy pata",
    costDetails: {
      totalReservationCost: 37500,
      minimumDownPayment: 7500,
      downPaymentPaid: 0,
    },
    status: "pending",
    paymentStatus: "pending",
    createdAt: new Date("2025-03-14"),
    updatedAt: new Date("2025-03-14"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678905"), // William Johnson (repeated)
    eventDetails: {
      type: "anniversary",
      date: new Date(2025, 9, 25),
      time: new Date(2025, 9, 25, 18, 0),
      numberOfGuests: 50,
      venue: "Iloilo Plaza",
      serviceType: "Plated Service",
      serviceHours: 5,
    },
    menuSelection: {
      soupOptions: ["Tinolang Manok"],
      saladOptions: ["Ensaladang Talong"],
      chickenOptions: [],
      porkOptions: ["Sisig"],
      beefOptions: ["Beef Mechado"],
      seafoodOptions: [],
      vegetableOptions: ["Pinakbet"],
      noodleOptions: [],
      dessertOptions: ["Halo-Halo", "Leche Flan"],
      beverageOptions: ["Sago't Gulaman"],
    },
    specialRequests: "Extra halo-halo",
    costDetails: {
      totalReservationCost: 25000,
      minimumDownPayment: 5000,
      downPaymentPaid: 5000,
    },
    status: "confirmed",
    paymentStatus: "partially_paid",
    createdAt: new Date("2025-03-15"),
    updatedAt: new Date("2025-03-17"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678906"), // Sarah Wilson (repeated)
    eventDetails: {
      type: "corporate",
      date: new Date(2025, 11, 10),
      time: new Date(2025, 11, 10, 9, 0),
      numberOfGuests: 85,
      venue: "Bohol Beach Club",
      serviceType: "Buffet",
      serviceHours: 8,
    },
    menuSelection: {
      soupOptions: ["Nilagang Baka"],
      saladOptions: ["Kinilaw na Tuna"],
      chickenOptions: ["Chicken Afritada", "Fried Chicken with Gravy"],
      porkOptions: ["Pork Adobo"],
      beefOptions: [],
      seafoodOptions: ["Beef Caldereta"],
      vegetableOptions: ["Laing"],
      noodleOptions: ["Pancit Canton"],
      dessertOptions: ["Bibingka"],
      beverageOptions: ["Buko Juice", "Tsokolate"],
    },
    specialRequests: "Low-sodium options",
    costDetails: {
      totalReservationCost: 42500,
      minimumDownPayment: 8500,
      downPaymentPaid: 0,
    },
    status: "pending",
    paymentStatus: "pending",
    createdAt: new Date("2025-03-16"),
    updatedAt: new Date("2025-03-16"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678907"), // David Lee (repeated)
    eventDetails: {
      type: "birthday",
      date: new Date(2025, 4, 20),
      time: new Date(2025, 4, 20, 15, 0),
      numberOfGuests: 35,
      venue: "La Union Surf Resort",
      serviceType: "Plated Service",
      serviceHours: 4,
    },
    menuSelection: {
      soupOptions: ["Sinigang na Baboy"],
      saladOptions: [],
      chickenOptions: ["Chicken Inasal"],
      porkOptions: [],
      beefOptions: ["Bistek Tagalog"],
      seafoodOptions: [],
      vegetableOptions: ["Ginisang Ampalaya"],
      noodleOptions: ["Pancit Bihon"],
      dessertOptions: ["Halo-Halo"],
      beverageOptions: ["Calamansi Juice"],
    },
    specialRequests: "No spicy food",
    costDetails: {
      totalReservationCost: 17500,
      minimumDownPayment: 3500,
      downPaymentPaid: 3500,
    },
    status: "confirmed",
    paymentStatus: "partially_paid",
    createdAt: new Date("2025-03-17"),
    updatedAt: new Date("2025-03-19"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678908"), // Laura Martinez (repeated)
    eventDetails: {
      type: "wedding",
      date: new Date(2025, 6, 30),
      time: new Date(2025, 6, 30, 17, 0),
      numberOfGuests: 60,
      venue: "Intramuros",
      serviceType: "Buffet",
      serviceHours: 6,
    },
    menuSelection: {
      soupOptions: ["Bulalo"],
      saladOptions: ["Lato Salad"],
      chickenOptions: ["Chicken Adobo"],
      porkOptions: ["Crispy Pata"],
      beefOptions: [],
      seafoodOptions: ["Beef Kare-Kare"],
      vegetableOptions: ["Pinakbet"],
      noodleOptions: [],
      dessertOptions: ["Biko", "Leche Flan"],
      beverageOptions: ["Sago't Gulaman"],
    },
    specialRequests: "Extra lechon",
    costDetails: {
      totalReservationCost: 30000,
      minimumDownPayment: 6000,
      downPaymentPaid: 0,
    },
    status: "pending",
    paymentStatus: "pending",
    createdAt: new Date("2025-03-18"),
    updatedAt: new Date("2025-03-18"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b12345678909"), // James Taylor (repeated)
    eventDetails: {
      type: "anniversary",
      date: new Date(2025, 8, 30),
      time: new Date(2025, 8, 30, 18, 0),
      numberOfGuests: 45,
      venue: "SM Megamall",
      serviceType: "Plated Service",
      serviceHours: 5,
    },
    menuSelection: {
      soupOptions: ["Tinolang Manok"],
      saladOptions: ["Ensaladang Talong"],
      chickenOptions: [],
      porkOptions: ["Sisig"],
      beefOptions: ["Beef Mechado"],
      seafoodOptions: [],
      vegetableOptions: ["Laing"],
      noodleOptions: ["Pancit Palabok"],
      dessertOptions: ["Halo-Halo"],
      beverageOptions: ["Tsokolate"],
    },
    specialRequests: "More dessert",
    costDetails: {
      totalReservationCost: 22500,
      minimumDownPayment: 4500,
      downPaymentPaid: 4500,
    },
    status: "confirmed",
    paymentStatus: "partially_paid",
    createdAt: new Date("2025-03-19"),
    updatedAt: new Date("2025-03-21"),
  },
  {
    customerId: new Types.ObjectId("605c72e9f1d2b1234567890a"), // Olivia Anderson (repeated)
    eventDetails: {
      type: "corporate",
      date: new Date(2025, 10, 25),
      time: new Date(2025, 10, 25, 9, 0),
      numberOfGuests: 95,
      venue: "Ayala Tower",
      serviceType: "Buffet",
      serviceHours: 10,
    },
    menuSelection: {
      soupOptions: ["Nilagang Baka"],
      saladOptions: ["Kinilaw na Tuna"],
      chickenOptions: ["Chicken Afritada"],
      porkOptions: ["Pork Adobo"],
      beefOptions: ["Beef Caldereta"],
      seafoodOptions: ["Beef Mechado"],
      vegetableOptions: [],
      noodleOptions: ["Pancit Canton"],
      dessertOptions: ["Leche Flan", "Bibingka"],
      beverageOptions: ["Buko Juice", "Sago't Gulaman"],
    },
    specialRequests: "Vegan options",
    costDetails: {
      totalReservationCost: 47500,
      minimumDownPayment: 9500,
      downPaymentPaid: 0,
    },
    status: "pending",
    paymentStatus: "pending",
    createdAt: new Date("2025-03-20"),
    updatedAt: new Date("2025-03-20"),
  },
];

export default reservationDummy;
