export const cateringPackages = [
  {
    name: "Set A - Basic Feast",
    description:
      "A simple yet satisfying selection of Filipino favorites for small gatherings.",
    available: true,
    pricePerPax: 350,
    minimumPax: 20,
    recommendedPax: 30,
    maximumPax: 50,
    options: [
      { category: "Soup", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Noodle", count: 1 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Basic table setup" },
      { typeOfCustomer: "Both", includes: "Disposable utensils and plates" },
      { typeOfCustomer: "Both", includes: "Service staff (2 personnel)" },
      { typeOfCustomer: "Both", includes: "Food warmers and serving utensils" },
      { typeOfCustomer: "Buffet", includes: "Self-service food stations" },
      { typeOfCustomer: "Buffet", includes: "Food labels and descriptions" },
      { typeOfCustomer: "Plated", includes: "4 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Professional waitstaff" },
      { typeOfCustomer: "Plated", includes: "Table-side service" },
      { typeOfCustomer: "Plated", includes: "Course-by-course serving" },
    ],
    imageUrl:
      "https://foodtray2go.com/wp-content/uploads/2022/09/image6-1024x764.jpg",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 4,
    serviceCharge: 100,
    packageType: "BuffetPlated",
    eventType: undefined,
    reviews: [],
    pricePerPaxWithServiceCharge: 370, // ((100 * 4) / 20) + 350 = 370
  },
  {
    name: "Set B - Family Celebration",
    description:
      "A hearty selection of dishes perfect for family celebrations and small parties.",
    available: true,
    pricePerPax: 450,
    minimumPax: 30,
    recommendedPax: 50,
    maximumPax: 80,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Noodle", count: 1 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Enhanced table setup" },
      { typeOfCustomer: "Both", includes: "Disposable utensils and plates" },
      { typeOfCustomer: "Both", includes: "Service staff (3 personnel)" },
      { typeOfCustomer: "Both", includes: "Food warmers and serving utensils" },
      { typeOfCustomer: "Both", includes: "Basic dessert station" },
      {
        typeOfCustomer: "Buffet",
        includes: "Buffet line setup with sneeze guards",
      },
      { typeOfCustomer: "Buffet", includes: "Replenishment of food as needed" },
      { typeOfCustomer: "Plated", includes: "4.5 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Professional waitstaff" },
      { typeOfCustomer: "Plated", includes: "Table-side service" },
      { typeOfCustomer: "Plated", includes: "Course-by-course serving" },
    ],
    imageUrl:
      "https://thesmartlocal.ph/wp-content/uploads/2020/04/kaintayo.jpg",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 4.5,
    serviceCharge: 100,
    packageType: "BuffetPlated",
    eventType: undefined,
    reviews: [],
    pricePerPaxWithServiceCharge: 465, // ((100 * 4.5) / 30) + 450 = 465
  },
  {
    name: "Set C - Fiesta Favorites",
    description:
      "A complete Filipino fiesta experience with a wide variety of traditional dishes.",
    available: true,
    pricePerPax: 550,
    minimumPax: 50,
    recommendedPax: 80,
    maximumPax: 120,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Noodle", count: 1 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Premium table setup" },
      {
        typeOfCustomer: "Both",
        includes: "Quality disposable utensils and plates",
      },
      { typeOfCustomer: "Both", includes: "Service staff (4 personnel)" },
      { typeOfCustomer: "Both", includes: "Food warmers and serving utensils" },
      { typeOfCustomer: "Both", includes: "Dessert station with 2 options" },
      { typeOfCustomer: "Both", includes: "Welcome drinks" },
      { typeOfCustomer: "Buffet", includes: "Decorated buffet stations" },
      { typeOfCustomer: "Buffet", includes: "Attendants at each food station" },
      { typeOfCustomer: "Plated", includes: "5 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Professional waitstaff" },
      { typeOfCustomer: "Plated", includes: "Table-side service" },
      { typeOfCustomer: "Plated", includes: "Course-by-course serving" },
    ],
    imageUrl:
      "https://philippinetourismusa.com/wp-content/uploads/2019/09/pinoy-heritage-kamayan-IMG_6193.jpg",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 5,
    serviceCharge: 100,
    packageType: "BuffetPlated",
    eventType: undefined,
    reviews: [],
    pricePerPaxWithServiceCharge: 560, // ((100 * 5) / 50) + 550 = 560
  },
  {
    name: "Set D - Premium Celebration",
    description:
      "An elevated dining experience featuring premium Filipino dishes for special occasions.",
    available: true,
    pricePerPax: 650,
    minimumPax: 50,
    recommendedPax: 100,
    maximumPax: 150,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 2 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Seafood", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Beverage", count: 1 },
    ],
    inclusions: [
      {
        typeOfCustomer: "Both",
        includes: "Elegant table setup with centerpieces",
      },
      {
        typeOfCustomer: "Both",
        includes: "Quality disposable utensils and plates",
      },
      { typeOfCustomer: "Both", includes: "Service staff (5 personnel)" },
      { typeOfCustomer: "Both", includes: "Food warmers and serving utensils" },
      { typeOfCustomer: "Both", includes: "Dessert station with 3 options" },
      { typeOfCustomer: "Both", includes: "Welcome drinks and iced tea" },
      { typeOfCustomer: "Both", includes: "Basic coffee station" },
      { typeOfCustomer: "Buffet", includes: "Premium buffet presentation" },
      { typeOfCustomer: "Buffet", includes: "Carving station with chef" },
      { typeOfCustomer: "Buffet", includes: "Plate clearing service" },
      { typeOfCustomer: "Plated", includes: "5.5 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Professional waitstaff" },
      { typeOfCustomer: "Plated", includes: "Table-side service" },
      { typeOfCustomer: "Plated", includes: "Course-by-course serving" },
    ],
    imageUrl:
      "https://juancarlo.ph/wp-content/uploads/2023/03/Private-Catering-Packages.jpg",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 5.5,
    serviceCharge: 100,
    packageType: "BuffetPlated",
    eventType: undefined,
    reviews: [],
    pricePerPaxWithServiceCharge: 661, // ((100 * 5.5) / 50) + 650 = 661
  },
  {
    name: "Set E - Grand Feast",
    description:
      "A grand Filipino feast featuring a comprehensive selection of dishes for large celebrations.",
    available: true,
    pricePerPax: 750,
    minimumPax: 80,
    recommendedPax: 120,
    maximumPax: 200,
    options: [
      { category: "Soup", count: 2 },
      { category: "Salad", count: 2 },
      { category: "Chicken", count: 2 },
      { category: "Pork", count: 2 },
      { category: "Beef", count: 1 },
      { category: "Seafood", count: 1 },
      { category: "Vegetable", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 2 },
      { category: "Beverage", count: 2 },
    ],
    inclusions: [
      {
        typeOfCustomer: "Both",
        includes: "Premium table setup with floral arrangements",
      },
      {
        typeOfCustomer: "Both",
        includes: "Quality disposable utensils and plates",
      },
      { typeOfCustomer: "Both", includes: "Service staff (7 personnel)" },
      { typeOfCustomer: "Both", includes: "Food warmers and serving utensils" },
      { typeOfCustomer: "Both", includes: "Dessert station with 4 options" },
      {
        typeOfCustomer: "Both",
        includes: "Welcome drinks and unlimited iced tea",
      },
      { typeOfCustomer: "Both", includes: "Coffee and tea station" },
      { typeOfCustomer: "Both", includes: "Fruit station" },
      {
        typeOfCustomer: "Buffet",
        includes: "Elegant buffet display with themed decor",
      },
      { typeOfCustomer: "Buffet", includes: "Live cooking demonstration" },
      {
        typeOfCustomer: "Buffet",
        includes: "Multiple food stations with attendants",
      },
      { typeOfCustomer: "Plated", includes: "6 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Professional waitstaff" },
      { typeOfCustomer: "Plated", includes: "Table-side service" },
      { typeOfCustomer: "Plated", includes: "Course-by-course serving" },
    ],
    imageUrl:
      "https://riverineplace.com/wp-content/uploads/2024/09/A-hotels-buffet-style-type-of-catering-service.jpg",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 6,
    serviceCharge: 100,
    packageType: "BuffetPlated",
    eventType: undefined,
    reviews: [],
    pricePerPaxWithServiceCharge: 758, // ((100 * 6) / 80) + 750 = 757.5 ≈ 758
  },
  {
    name: "Set F - Royal Filipino Banquet",
    description:
      "The ultimate Filipino banquet experience featuring our finest dishes and premium service.",
    available: true,
    pricePerPax: 950,
    minimumPax: 100,
    recommendedPax: 150,
    maximumPax: 300,
    options: [
      { category: "Soup", count: 2 },
      { category: "Salad", count: 2 },
      { category: "Chicken", count: 2 },
      { category: "Pork", count: 2 },
      { category: "Beef", count: 2 },
      { category: "Seafood", count: 2 },
      { category: "Vegetable", count: 2 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 3 },
      { category: "Beverage", count: 3 },
    ],
    inclusions: [
      {
        typeOfCustomer: "Both",
        includes: "Luxury table setup with premium decorations",
      },
      { typeOfCustomer: "Both", includes: "Fine dining utensils and plates" },
      { typeOfCustomer: "Both", includes: "Service staff (10 personnel)" },
      { typeOfCustomer: "Both", includes: "Food warmers and serving utensils" },
      {
        typeOfCustomer: "Both",
        includes: "Premium dessert station with 5 options",
      },
      {
        typeOfCustomer: "Both",
        includes: "Welcome cocktails and unlimited beverages",
      },
      { typeOfCustomer: "Both", includes: "Premium coffee and tea station" },
      { typeOfCustomer: "Both", includes: "Fruit and cheese station" },
      { typeOfCustomer: "Both", includes: "Live cooking station" },
      { typeOfCustomer: "Both", includes: "Ice cream station" },
      {
        typeOfCustomer: "Buffet",
        includes: "Luxury buffet presentation with ice sculptures",
      },
      { typeOfCustomer: "Buffet", includes: "Multiple themed food stations" },
      {
        typeOfCustomer: "Buffet",
        includes: "Chef's special interactive stations",
      },
      {
        typeOfCustomer: "Buffet",
        includes: "Premium food display arrangements",
      },
      { typeOfCustomer: "Plated", includes: "6.5 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Table-side service" },
      { typeOfCustomer: "Plated", includes: "Course-by-course serving" },
    ],
    imageUrl: "https://maviscatering.com/img/bg-img/3.jpg",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 6.5,
    serviceCharge: 100,
    packageType: "BuffetPlated",
    eventType: undefined,
    reviews: [],
    pricePerPaxWithServiceCharge: 965, // ((100 * 6.5) / 100) + 950 = 965
  },
  //Birthday
  {
    name: "Birthday Celebration - Basic",
    description: "A fun and festive package perfect for birthday celebrations.",
    available: true,
    pricePerPax: 450,
    minimumPax: 30,
    recommendedPax: 40,
    maximumPax: 60,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 1 },
      { category: "Beverage", count: 1 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Unlimited steamed rice" },
      { typeOfCustomer: "Both", includes: "Basic birthday setup" },
      { typeOfCustomer: "Both", includes: "Disposable utensils and plates" },
      { typeOfCustomer: "Both", includes: "Service staff (3 personnel)" },
      {
        typeOfCustomer: "Both",
        includes: "Food warmers and serving utensils",
      },
      { typeOfCustomer: "Both", includes: "Birthday cake table setup" },
      { typeOfCustomer: "Both", includes: "Welcome drinks" },
      { typeOfCustomer: "Buffet", includes: "Simple buffet setup" },
      { typeOfCustomer: "Buffet", includes: "Birthday-themed food labels" },
      { typeOfCustomer: "Plated", includes: "Individual table service" },
      { typeOfCustomer: "Plated", includes: "Personalized menu cards" },
      { typeOfCustomer: "Plated", includes: "Dedicated server per 10 guests" },
      { typeOfCustomer: "Plated", includes: "Course-by-course serving" },
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 4,
    serviceCharge: 100,
    packageType: "Event",
    eventType: "Birthday",
    reviews: [],
    pricePerPaxWithServiceCharge: 463, // ((100 * 4) / 30) + 450 = 463.33 ≈ 463
  },
  {
    name: "Birthday Celebration - Premium",
    description:
      "An enhanced birthday package with more food options and better service.",
    available: true,
    pricePerPax: 550,
    minimumPax: 50,
    recommendedPax: 100,
    maximumPax: 150,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 2 },
      { category: "Beverage", count: 2 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Unlimited steamed rice" },
      {
        typeOfCustomer: "Both",
        includes: "Premium birthday setup with balloons",
      },
      {
        typeOfCustomer: "Both",
        includes: "Quality disposable utensils and plates",
      },
      { typeOfCustomer: "Both", includes: "Service staff (4 personnel)" },
      {
        typeOfCustomer: "Both",
        includes: "Food warmers and serving utensils",
      },
      {
        typeOfCustomer: "Both",
        includes: "Birthday cake table with special decoration",
      },
      { typeOfCustomer: "Both", includes: "Welcome drinks and iced tea" },
      { typeOfCustomer: "Both", includes: "Basic photo area" },
      { typeOfCustomer: "Buffet", includes: "Enhanced buffet presentation" },
      { typeOfCustomer: "Buffet", includes: "Dedicated buffet attendants" },
      { typeOfCustomer: "Buffet", includes: "Themed food display" },
      { typeOfCustomer: "Plated", includes: "4 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Dedicated server per 8 guests" },
      { typeOfCustomer: "Plated", includes: "Personalized menu cards" },
      { typeOfCustomer: "Plated", includes: "Synchronized serving" },
      { typeOfCustomer: "Plated", includes: "Water and wine service" },
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 5,
    serviceCharge: 100,
    packageType: "Event",
    eventType: "Birthday",
    reviews: [],
    pricePerPaxWithServiceCharge: 560, // ((100 * 5) / 50) + 550 = 560
  },
  {
    name: "Birthday Celebration - Deluxe",
    description:
      "A comprehensive birthday package for a memorable celebration.",
    available: true,
    pricePerPax: 650,
    minimumPax: 80,
    recommendedPax: 120,
    maximumPax: 160,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 2 },
      { category: "Chicken", count: 2 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Seafood", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 2 },
      { category: "Beverage", count: 2 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Unlimited steamed rice" },
      {
        typeOfCustomer: "Both",
        includes: "Deluxe birthday setup with themed decorations",
      },
      {
        typeOfCustomer: "Both",
        includes: "Quality disposable utensils and plates",
      },
      { typeOfCustomer: "Both", includes: "Service staff (6 personnel)" },
      {
        typeOfCustomer: "Both",
        includes: "Food warmers and serving utensils",
      },
      { typeOfCustomer: "Both", includes: "Elaborate birthday cake table" },
      {
        typeOfCustomer: "Both",
        includes: "Welcome drinks and unlimited iced tea",
      },
      { typeOfCustomer: "Both", includes: "Dessert station" },
      { typeOfCustomer: "Both", includes: "Photo area with props" },
      {
        typeOfCustomer: "Buffet",
        includes: "Premium buffet stations with birthday theme",
      },
      { typeOfCustomer: "Buffet", includes: "Food station with live cooking" },
      {
        typeOfCustomer: "Buffet",
        includes: "Customized food labels with birthday motif",
      },
      { typeOfCustomer: "Plated", includes: "5 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Dedicated server per 6 guests" },
      { typeOfCustomer: "Plated", includes: "Premium menu cards" },
      { typeOfCustomer: "Plated", includes: "Synchronized serving" },
      { typeOfCustomer: "Plated", includes: "Full beverage service" },
      { typeOfCustomer: "Plated", includes: "White glove service" },
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 6,
    serviceCharge: 100,
    packageType: "Event",
    eventType: "Birthday",
    reviews: [],
    pricePerPaxWithServiceCharge: 658, // ((100 * 6) / 80) + 650 = 657.5 ≈ 658
  },
  {
    name: "Birthday Celebration - Ultimate",
    description:
      "The ultimate birthday package for an unforgettable celebration.",
    available: true,
    pricePerPax: 850,
    minimumPax: 100,
    recommendedPax: 150,
    maximumPax: 300,
    options: [
      { category: "Soup", count: 2 },
      { category: "Salad", count: 2 },
      { category: "Chicken", count: 2 },
      { category: "Pork", count: 2 },
      { category: "Beef", count: 1 },
      { category: "Seafood", count: 1 },
      { category: "Vegetable", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 3 },
      { category: "Beverage", count: 3 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Unlimited steamed rice" },
      {
        typeOfCustomer: "Both",
        includes: "Ultimate birthday setup with premium decorations",
      },
      { typeOfCustomer: "Both", includes: "Fine dining utensils and plates" },
      { typeOfCustomer: "Both", includes: "Service staff (8 personnel)" },
      {
        typeOfCustomer: "Both",
        includes: "Food warmers and serving utensils",
      },
      { typeOfCustomer: "Both", includes: "Luxury birthday cake table" },
      {
        typeOfCustomer: "Both",
        includes: "Welcome cocktails and unlimited beverages",
      },
      { typeOfCustomer: "Both", includes: "Premium dessert station" },
      { typeOfCustomer: "Both", includes: "Professional photo area" },
      { typeOfCustomer: "Both", includes: "Live cooking station" },
      { typeOfCustomer: "Both", includes: "Ice cream station" },
      { typeOfCustomer: "Both", includes: "Basic entertainment coordination" },
      {
        typeOfCustomer: "Buffet",
        includes: "Luxury buffet presentation with themed displays",
      },
      {
        typeOfCustomer: "Buffet",
        includes: "Multiple interactive food stations",
      },
      {
        typeOfCustomer: "Buffet",
        includes: "Chef's special birthday menu presentation",
      },
      { typeOfCustomer: "Buffet", includes: "VIP section at buffet line" },
      { typeOfCustomer: "Plated", includes: "6 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Dedicated server per 5 guests" },
      { typeOfCustomer: "Plated", includes: "Luxury menu presentation" },
      {
        typeOfCustomer: "Plated",
        includes: "Synchronized multi-course serving",
      },
      { typeOfCustomer: "Plated", includes: "Premium beverage service" },
      { typeOfCustomer: "Plated", includes: "White glove service" },
      { typeOfCustomer: "Plated", includes: "Personal sommelier service" },
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 8,
    serviceCharge: 100,
    packageType: "Event",
    eventType: "Birthday",
    reviews: [],
    pricePerPaxWithServiceCharge: 930, // ((100 * 8) / 100) + 850 = 930
  },
  //Wedding
  {
    name: "Wedding Reception - Essential",
    description:
      "An essential wedding reception package for intimate celebrations.",
    available: true,
    pricePerPax: 550,
    minimumPax: 50,
    recommendedPax: 150,
    maximumPax: 300,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 1 },
      { category: "Beverage", count: 1 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Unlimited steamed rice" },
      { typeOfCustomer: "Both", includes: "Basic wedding reception setup" },
      {
        typeOfCustomer: "Both",
        includes: "Quality disposable utensils and plates",
      },
      { typeOfCustomer: "Both", includes: "Service staff (4 personnel)" },
      {
        typeOfCustomer: "Both",
        includes: "Food warmers and serving utensils",
      },
      { typeOfCustomer: "Both", includes: "Cake table setup" },
      { typeOfCustomer: "Both", includes: "Welcome drinks" },
      { typeOfCustomer: "Both", includes: "Basic toast setup" },
      {
        typeOfCustomer: "Buffet",
        includes: "Simple wedding-themed buffet setup",
      },
      { typeOfCustomer: "Buffet", includes: "Organized buffet line flow" },
      { typeOfCustomer: "Plated", includes: "4 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Dedicated server per 10 guests" },
      { typeOfCustomer: "Plated", includes: "Basic menu cards" },
      { typeOfCustomer: "Plated", includes: "Course-by-course serving" },
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 4,
    serviceCharge: 100,
    packageType: "Event",
    eventType: "Wedding",
    reviews: [],
    pricePerPaxWithServiceCharge: 558, // ((100 * 4) / 50) + 550 = 558
  },
  {
    name: "Wedding Reception - Classic",
    description: "A classic wedding reception package with enhanced offerings.",
    available: true,
    pricePerPax: 750,
    minimumPax: 80,
    recommendedPax: 120,
    maximumPax: 160,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Seafood", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 2 },
      { category: "Beverage", count: 2 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Unlimited steamed rice" },
      {
        typeOfCustomer: "Both",
        includes:
          "Classic wedding reception setup with basic floral arrangements",
      },
      {
        typeOfCustomer: "Both",
        includes: "Quality disposable utensils and plates",
      },
      { typeOfCustomer: "Both", includes: "Service staff (6 personnel)" },
      {
        typeOfCustomer: "Both",
        includes: "Food warmers and serving utensils",
      },
      { typeOfCustomer: "Both", includes: "Elegant cake table setup" },
      { typeOfCustomer: "Both", includes: "Welcome drinks and iced tea" },
      { typeOfCustomer: "Both", includes: "Toast setup with sparkling juice" },
      { typeOfCustomer: "Both", includes: "Basic couple's table decoration" },
      {
        typeOfCustomer: "Buffet",
        includes: "Elegant buffet setup with wedding theme",
      },
      { typeOfCustomer: "Buffet", includes: "Dedicated buffet attendants" },
      { typeOfCustomer: "Buffet", includes: "Coordinated food service timing" },
      { typeOfCustomer: "Plated", includes: "5 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Dedicated server per 8 guests" },
      { typeOfCustomer: "Plated", includes: "Elegant menu cards" },
      { typeOfCustomer: "Plated", includes: "Synchronized serving" },
      { typeOfCustomer: "Plated", includes: "Water and wine service" },
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 5,
    serviceCharge: 100,
    packageType: "Event",
    eventType: "Wedding",
    reviews: [],
    pricePerPaxWithServiceCharge: 756, // ((100 * 5) / 80) + 750 = 756.25 ≈ 756
  },
  {
    name: "Wedding Reception - Elegant",
    description:
      "An elegant wedding reception package for a beautiful celebration.",
    available: true,
    pricePerPax: 950,
    minimumPax: 100,
    recommendedPax: 150,
    maximumPax: 200,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 2 },
      { category: "Chicken", count: 2 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Seafood", count: 1 },
      { category: "Vegetable", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 3 },
      { category: "Beverage", count: 2 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Unlimited steamed rice" },
      {
        typeOfCustomer: "Both",
        includes: "Elegant wedding reception setup with floral arrangements",
      },
      { typeOfCustomer: "Both", includes: "Fine dining utensils and plates" },
      { typeOfCustomer: "Both", includes: "Service staff (8 personnel)" },
      {
        typeOfCustomer: "Both",
        includes: "Food warmers and serving utensils",
      },
      { typeOfCustomer: "Both", includes: "Premium cake table setup" },
      {
        typeOfCustomer: "Both",
        includes: "Welcome cocktails and unlimited beverages",
      },
      { typeOfCustomer: "Both", includes: "Toast setup with sparkling wine" },
      {
        typeOfCustomer: "Both",
        includes: "Elegant couple's table decoration",
      },
      { typeOfCustomer: "Both", includes: "Dessert station" },
      { typeOfCustomer: "Both", includes: "Coffee and tea station" },
      {
        typeOfCustomer: "Buffet",
        includes: "Premium wedding-themed buffet presentation",
      },
      {
        typeOfCustomer: "Buffet",
        includes: "Multiple food stations with attendants",
      },
      {
        typeOfCustomer: "Buffet",
        includes: "Elegant food display with decorative elements",
      },
      { typeOfCustomer: "Buffet", includes: "Champagne fountain" },
      { typeOfCustomer: "Plated", includes: "6 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Dedicated server per 6 guests" },
      {
        typeOfCustomer: "Plated",
        includes: "Premium menu cards with gold accents",
      },
      {
        typeOfCustomer: "Plated",
        includes: "Synchronized multi-course serving",
      },
      { typeOfCustomer: "Plated", includes: "Full beverage service" },
      { typeOfCustomer: "Plated", includes: "White glove service" },
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 6,
    serviceCharge: 100,
    packageType: "Event",
    eventType: "Wedding",
    reviews: [],
    pricePerPaxWithServiceCharge: 960, // ((100 * 6) / 100) + 950 = 960
  },
  {
    name: "Wedding Reception - Luxurious",
    description:
      "A luxurious wedding reception package for an unforgettable celebration.",
    available: true,
    pricePerPax: 1250,
    minimumPax: 150,
    recommendedPax: 220,
    maximumPax: 300,
    options: [
      { category: "Soup", count: 2 },
      { category: "Salad", count: 2 },
      { category: "Chicken", count: 2 },
      { category: "Pork", count: 2 },
      { category: "Beef", count: 2 },
      { category: "Seafood", count: 2 },
      { category: "Vegetable", count: 2 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 4 },
      { category: "Beverage", count: 3 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Unlimited steamed rice" },
      {
        typeOfCustomer: "Both",
        includes:
          "Luxurious wedding reception setup with premium floral arrangements",
      },
      { typeOfCustomer: "Both", includes: "Fine dining utensils and plates" },
      { typeOfCustomer: "Both", includes: "Service staff (12 personnel)" },
      {
        typeOfCustomer: "Both",
        includes: "Food warmers and serving utensils",
      },
      { typeOfCustomer: "Both", includes: "Luxury cake table setup" },
      {
        typeOfCustomer: "Both",
        includes: "Welcome champagne and unlimited premium beverages",
      },
      { typeOfCustomer: "Both", includes: "Toast setup with champagne" },
      { typeOfCustomer: "Both", includes: "Luxury couple's table decoration" },
      { typeOfCustomer: "Both", includes: "Premium dessert station" },
      { typeOfCustomer: "Both", includes: "Premium coffee and tea station" },
      { typeOfCustomer: "Both", includes: "Chocolate fountain" },
      { typeOfCustomer: "Both", includes: "Ice cream station" },
      { typeOfCustomer: "Both", includes: "Live cooking station" },
      {
        typeOfCustomer: "Both",
        includes: "Basic coordination with other vendors",
      },
      {
        typeOfCustomer: "Buffet",
        includes: "Luxury buffet presentation with ice sculptures",
      },
      {
        typeOfCustomer: "Buffet",
        includes: "Gourmet food stations with specialized chefs",
      },
      {
        typeOfCustomer: "Buffet",
        includes: "Premium food display with wedding theme",
      },
      { typeOfCustomer: "Buffet", includes: "VIP priority service at buffet" },
      { typeOfCustomer: "Plated", includes: "8 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Dedicated server per 4 guests" },
      { typeOfCustomer: "Plated", includes: "Luxury menu presentation" },
      {
        typeOfCustomer: "Plated",
        includes: "Synchronized multi-course serving",
      },
      { typeOfCustomer: "Plated", includes: "Premium beverage service" },
      { typeOfCustomer: "Plated", includes: "White glove service" },
      { typeOfCustomer: "Plated", includes: "Personal sommelier service" },
      { typeOfCustomer: "Plated", includes: "Custom plate presentation" },
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 8,
    serviceCharge: 100,
    packageType: "Event",
    eventType: "Wedding",
    reviews: [],
    pricePerPaxWithServiceCharge: 1303, // ((100 * 8) / 150) + 1250 = 1303.33 ≈ 1303
  },

  //Corporate
  {
    name: "Corporate Event - Basic",
    description:
      "A basic corporate event package suitable for meetings and small gatherings.",
    available: true,
    pricePerPax: 450,
    minimumPax: 30,
    recommendedPax: 45,
    maximumPax: 60,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 1 },
      { category: "Beverage", count: 1 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Unlimited steamed rice" },
      { typeOfCustomer: "Both", includes: "Basic corporate setup" },
      {
        typeOfCustomer: "Both",
        includes: "Quality disposable utensils and plates",
      },
      { typeOfCustomer: "Both", includes: "Service staff (3 personnel)" },
      {
        typeOfCustomer: "Both",
        includes: "Food warmers and serving utensils",
      },
      { typeOfCustomer: "Both", includes: "Water station" },
      { typeOfCustomer: "Both", includes: "Basic coffee and tea station" },
      {
        typeOfCustomer: "Buffet",
        includes: "Simple corporate-themed buffet setup",
      },
      { typeOfCustomer: "Buffet", includes: "Organized food labels" },
      { typeOfCustomer: "Plated", includes: "3 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Dedicated server per 12 guests" },
      { typeOfCustomer: "Plated", includes: "Simple menu cards" },
      { typeOfCustomer: "Plated", includes: "Course-by-course serving" },
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 4,
    serviceCharge: 100,
    packageType: "Event",
    eventType: "Corporate",
    reviews: [],
    pricePerPaxWithServiceCharge: 463, // ((100 * 4) / 30) + 450 = 463.33 ≈ 463
  },
  {
    name: "Corporate Event - Standard",
    description:
      "A standard corporate event package for professional gatherings.",
    available: true,
    pricePerPax: 550,
    minimumPax: 50,
    recommendedPax: 75,
    maximumPax: 100,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 2 },
      { category: "Beverage", count: 2 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Unlimited steamed rice" },
      { typeOfCustomer: "Both", includes: "Professional corporate setup" },
      {
        typeOfCustomer: "Both",
        includes: "Quality disposable utensils and plates",
      },
      { typeOfCustomer: "Both", includes: "Service staff (4 personnel)" },
      {
        typeOfCustomer: "Both",
        includes: "Food warmers and serving utensils",
      },
      { typeOfCustomer: "Both", includes: "Water station" },
      { typeOfCustomer: "Both", includes: "Coffee and tea station" },
      { typeOfCustomer: "Both", includes: "Light snacks during breaks" },
      {
        typeOfCustomer: "Buffet",
        includes: "Professional buffet setup with corporate branding",
      },
      { typeOfCustomer: "Buffet", includes: "Buffet attendants" },
      { typeOfCustomer: "Buffet", includes: "Efficient food replenishment" },
      { typeOfCustomer: "Plated", includes: "4 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Dedicated server per 10 guests" },
      { typeOfCustomer: "Plated", includes: "Professional menu cards" },
      { typeOfCustomer: "Plated", includes: "Synchronized serving" },
      { typeOfCustomer: "Plated", includes: "Water service" },
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 5,
    serviceCharge: 100,
    packageType: "Event",
    eventType: "Corporate",
    reviews: [],
    pricePerPaxWithServiceCharge: 560, // ((100 * 5) / 50) + 550 = 560
  },
  {
    name: "Corporate Event - Executive",
    description:
      "An executive corporate event package for important business functions.",
    available: true,
    pricePerPax: 650,
    minimumPax: 80,
    recommendedPax: 120,
    maximumPax: 160,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 2 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Seafood", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 2 },
      { category: "Beverage", count: 2 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Unlimited steamed rice" },
      { typeOfCustomer: "Both", includes: "Executive corporate setup" },
      { typeOfCustomer: "Both", includes: "Fine dining utensils and plates" },
      { typeOfCustomer: "Both", includes: "Service staff (6 personnel)" },
      {
        typeOfCustomer: "Both",
        includes: "Food warmers and serving utensils",
      },
      { typeOfCustomer: "Both", includes: "Water station with lemon" },
      { typeOfCustomer: "Both", includes: "Premium coffee and tea station" },
      { typeOfCustomer: "Both", includes: "Morning and afternoon snacks" },
      { typeOfCustomer: "Both", includes: "Dessert station" },
      { typeOfCustomer: "Buffet", includes: "Executive buffet presentation" },
      { typeOfCustomer: "Buffet", includes: "Corporate-branded food displays" },
      { typeOfCustomer: "Buffet", includes: "Chef-attended carving station" },
      {
        typeOfCustomer: "Buffet",
        includes: "Premium food labels with descriptions",
      },
      { typeOfCustomer: "Plated", includes: "5 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Dedicated server per 8 guests" },
      { typeOfCustomer: "Plated", includes: "Executive menu presentation" },
      {
        typeOfCustomer: "Plated",
        includes: "Synchronized multi-course serving",
      },
      { typeOfCustomer: "Plated", includes: "Full beverage service" },
      { typeOfCustomer: "Plated", includes: "Professional service staff" },
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 6,
    serviceCharge: 100,
    packageType: "Event",
    eventType: "Corporate",
    reviews: [],
    pricePerPaxWithServiceCharge: 658, // ((100 * 6) / 80) + 650 = 657.5 ≈ 658
  },
  {
    name: "Corporate Event - Premium",
    description:
      "A premium corporate event package for high-profile business functions.",
    available: true,
    pricePerPax: 850,
    minimumPax: 100,
    recommendedPax: 150,
    maximumPax: 200,
    options: [
      { category: "Soup", count: 2 },
      { category: "Salad", count: 2 },
      { category: "Chicken", count: 2 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Seafood", count: 1 },
      { category: "Vegetable", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 3 },
      { category: "Beverage", count: 3 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Unlimited steamed rice" },
      {
        typeOfCustomer: "Both",
        includes: "Premium corporate setup with branding options",
      },
      { typeOfCustomer: "Both", includes: "Fine dining utensils and plates" },
      { typeOfCustomer: "Both", includes: "Service staff (8 personnel)" },
      {
        typeOfCustomer: "Both",
        includes: "Food warmers and serving utensils",
      },
      { typeOfCustomer: "Both", includes: "Infused water station" },
      { typeOfCustomer: "Both", includes: "Premium coffee and tea station" },
      {
        typeOfCustomer: "Both",
        includes: "Gourmet morning and afternoon snacks",
      },
      { typeOfCustomer: "Both", includes: "Premium dessert station" },
      { typeOfCustomer: "Both", includes: "Fruit and cheese station" },
      { typeOfCustomer: "Both", includes: "Basic technical support" },
      {
        typeOfCustomer: "Buffet",
        includes: "Premium corporate-branded buffet stations",
      },
      { typeOfCustomer: "Buffet", includes: "Multiple gourmet food stations" },
      { typeOfCustomer: "Buffet", includes: "Live cooking demonstrations" },
      { typeOfCustomer: "Buffet", includes: "Executive priority service" },
      { typeOfCustomer: "Plated", includes: "6 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Dedicated server per 6 guests" },
      { typeOfCustomer: "Plated", includes: "Premium menu presentation" },
      {
        typeOfCustomer: "Plated",
        includes: "Synchronized multi-course serving",
      },
      { typeOfCustomer: "Plated", includes: "Premium beverage service" },
      { typeOfCustomer: "Plated", includes: "White glove service" },
      {
        typeOfCustomer: "Plated",
        includes: "Custom corporate branding on service items",
      },
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 8,
    serviceCharge: 100,
    packageType: "Event",
    eventType: "Corporate",
    reviews: [],
    pricePerPaxWithServiceCharge: 930, // ((100 * 8) / 100) + 850 = 930
  },
  //Graduation
  {
    name: "Graduation Celebration - Basic",
    description: "A basic graduation celebration package for the new graduate.",
    available: true,
    pricePerPax: 400,
    minimumPax: 30,
    recommendedPax: 45,
    maximumPax: 60,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 1 },
      { category: "Beverage", count: 1 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Unlimited steamed rice" },
      { typeOfCustomer: "Both", includes: "Basic graduation setup" },
      {
        typeOfCustomer: "Both",
        includes: "Quality disposable utensils and plates",
      },
      { typeOfCustomer: "Both", includes: "Service staff (3 personnel)" },
      {
        typeOfCustomer: "Both",
        includes: "Food warmers and serving utensils",
      },
      { typeOfCustomer: "Both", includes: "Graduation cake table setup" },
      { typeOfCustomer: "Both", includes: "Welcome drinks" },
      {
        typeOfCustomer: "Buffet",
        includes: "Simple graduation-themed buffet setup",
      },
      { typeOfCustomer: "Buffet", includes: "Basic food labels" },
      { typeOfCustomer: "Plated", includes: "3 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Dedicated server per 12 guests" },
      { typeOfCustomer: "Plated", includes: "Simple menu cards" },
      { typeOfCustomer: "Plated", includes: "Course-by-course serving" },
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 4,
    serviceCharge: 100,
    packageType: "Event",
    eventType: "Graduation",
    reviews: [],
    pricePerPaxWithServiceCharge: 413, // ((100 * 4) / 30) + 400 = 413.33 ≈ 413
  },
  {
    name: "Graduation Celebration - Standard",
    description:
      "A standard graduation celebration package for a memorable achievement.",
    available: true,
    pricePerPax: 500,
    minimumPax: 50,
    recommendedPax: 75,
    maximumPax: 100,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 1 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 2 },
      { category: "Beverage", count: 2 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Unlimited steamed rice" },
      {
        typeOfCustomer: "Both",
        includes: "Standard graduation setup with basic decorations",
      },
      {
        typeOfCustomer: "Both",
        includes: "Quality disposable utensils and plates",
      },
      { typeOfCustomer: "Both", includes: "Service staff (4 personnel)" },
      {
        typeOfCustomer: "Both",
        includes: "Food warmers and serving utensils",
      },
      {
        typeOfCustomer: "Both",
        includes: "Graduation cake table with special decoration",
      },
      { typeOfCustomer: "Both", includes: "Welcome drinks and iced tea" },
      { typeOfCustomer: "Both", includes: "Basic photo area" },
      {
        typeOfCustomer: "Buffet",
        includes: "Graduation-themed buffet presentation",
      },
      { typeOfCustomer: "Buffet", includes: "Dedicated buffet attendants" },
      { typeOfCustomer: "Buffet", includes: "Organized food stations" },
      { typeOfCustomer: "Plated", includes: "4 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Dedicated server per 10 guests" },
      { typeOfCustomer: "Plated", includes: "Themed menu cards" },
      { typeOfCustomer: "Plated", includes: "Synchronized serving" },
      { typeOfCustomer: "Plated", includes: "Water and juice service" },
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 5,
    serviceCharge: 100,
    packageType: "Event",
    eventType: "Graduation",
    reviews: [],
    pricePerPaxWithServiceCharge: 510, // ((100 * 5) / 50) + 500 = 510
  },
  {
    name: "Graduation Celebration - Deluxe",
    description:
      "A deluxe graduation celebration package for an important milestone.",
    available: true,
    pricePerPax: 600,
    minimumPax: 80,
    recommendedPax: 120,
    maximumPax: 160,
    options: [
      { category: "Soup", count: 1 },
      { category: "Salad", count: 2 },
      { category: "Chicken", count: 1 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Seafood", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 2 },
      { category: "Beverage", count: 2 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Unlimited steamed rice" },
      {
        typeOfCustomer: "Both",
        includes: "Deluxe graduation setup with themed decorations",
      },
      {
        typeOfCustomer: "Both",
        includes: "Quality disposable utensils and plates",
      },
      { typeOfCustomer: "Both", includes: "Service staff (6 personnel)" },
      {
        typeOfCustomer: "Both",
        includes: "Food warmers and serving utensils",
      },
      { typeOfCustomer: "Both", includes: "Elaborate graduation cake table" },
      {
        typeOfCustomer: "Both",
        includes: "Welcome drinks and unlimited iced tea",
      },
      { typeOfCustomer: "Both", includes: "Dessert station" },
      { typeOfCustomer: "Both", includes: "Photo area with props" },
      {
        typeOfCustomer: "Buffet",
        includes: "Premium graduation-themed buffet stations",
      },
      { typeOfCustomer: "Buffet", includes: "Customized food displays" },
      { typeOfCustomer: "Buffet", includes: "Dedicated station attendants" },
      {
        typeOfCustomer: "Buffet",
        includes: "Graduate's favorite dishes highlighted",
      },
      { typeOfCustomer: "Plated", includes: "5 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Dedicated server per 8 guests" },
      { typeOfCustomer: "Plated", includes: "Custom graduation menu cards" },
      {
        typeOfCustomer: "Plated",
        includes: "Synchronized multi-course serving",
      },
      { typeOfCustomer: "Plated", includes: "Full beverage service" },
      { typeOfCustomer: "Plated", includes: "Professional service staff" },
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 6,
    serviceCharge: 100,
    packageType: "Event",
    eventType: "Graduation",
    reviews: [],
    pricePerPaxWithServiceCharge: 608, // ((100 * 6) / 80) + 600 = 607.5 ≈ 608
  },
  {
    name: "Graduation Celebration - Premium",
    description:
      "A premium graduation celebration package for an unforgettable achievement.",
    available: true,
    pricePerPax: 750,
    minimumPax: 100,
    recommendedPax: 150,
    maximumPax: 200,
    options: [
      { category: "Soup", count: 2 },
      { category: "Salad", count: 2 },
      { category: "Chicken", count: 2 },
      { category: "Pork", count: 1 },
      { category: "Beef", count: 1 },
      { category: "Seafood", count: 1 },
      { category: "Vegetable", count: 1 },
      { category: "Noodle", count: 1 },
      { category: "Dessert", count: 3 },
      { category: "Beverage", count: 3 },
    ],
    inclusions: [
      { typeOfCustomer: "Both", includes: "Unlimited steamed rice" },
      {
        typeOfCustomer: "Both",
        includes: "Premium graduation setup with elegant decorations",
      },
      { typeOfCustomer: "Both", includes: "Fine dining utensils and plates" },
      { typeOfCustomer: "Both", includes: "Service staff (8 personnel)" },
      {
        typeOfCustomer: "Both",
        includes: "Food warmers and serving utensils",
      },
      { typeOfCustomer: "Both", includes: "Luxury graduation cake table" },
      {
        typeOfCustomer: "Both",
        includes: "Welcome cocktails and unlimited beverages",
      },
      { typeOfCustomer: "Both", includes: "Premium dessert station" },
      { typeOfCustomer: "Both", includes: "Professional photo area" },
      { typeOfCustomer: "Both", includes: "Live cooking station" },
      { typeOfCustomer: "Both", includes: "Basic entertainment coordination" },
      {
        typeOfCustomer: "Buffet",
        includes: "Luxury graduation-themed buffet presentation",
      },
      { typeOfCustomer: "Buffet", includes: "Multiple gourmet food stations" },
      { typeOfCustomer: "Buffet", includes: "Interactive food displays" },
      {
        typeOfCustomer: "Buffet",
        includes: "VIP service for graduate and family",
      },
      { typeOfCustomer: "Plated", includes: "6 hours of table service" },
      { typeOfCustomer: "Plated", includes: "Dedicated server per 6 guests" },
      {
        typeOfCustomer: "Plated",
        includes: "Premium graduation-themed menu presentation",
      },
      {
        typeOfCustomer: "Plated",
        includes: "Synchronized multi-course serving",
      },
      { typeOfCustomer: "Plated", includes: "Premium beverage service" },
      { typeOfCustomer: "Plated", includes: "White glove service" },
      {
        typeOfCustomer: "Plated",
        includes: "Personalized service for graduate and family",
      },
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    ratingCount: 200,
    serviceHours: 8,
    serviceCharge: 100,
    packageType: "Event",
    eventType: "Graduation",
    reviews: [],
    pricePerPaxWithServiceCharge: 830, // ((100 * 8) / 100) + 750 = 830
  },
];
